### ISSUE TITLE
Issues with dates

### ISSUE THREAD

**Issue by olivierberten** [ztlxltl/FamilyTreeView#7]
Sorry for not being more specific but I can't figure out what the problem actually is... It works correctly with the example tree but with any of my trees (even with a 3 people one I just created for testing this), when I try to open the panel for individuals, I get this error:

```
2024-12-26 08:42:50.005: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/home/me/.gramps/gramps52/plugins/FamilyTreeView/family_tree_view_info_widget_manager.py", line 298, in <lambda>
    open_panel_button.connect("clicked", lambda*_: self.widget_manager.panel_manager.open_person_panel(person_handle))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.gramps/gramps52/plugins/FamilyTreeView/family_tree_view_panel_manager.py", line 121, in open_person_panel
    timeline = FamilyTreeViewTimeline(self.widget_manager, person, self.panel_scrolled)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.gramps/gramps52/plugins/FamilyTreeView/family_tree_view_timeline.py", line 114, in __init__
    has_non_primary_events = any(
                             ^^^^
  File "/home/me/.gramps/gramps52/plugins/FamilyTreeView/family_tree_view_timeline.py", line 117, in <genexpr>
    if ref_will_be_on_timeline(ref)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.gramps/gramps52/plugins/FamilyTreeView/family_tree_view_timeline.py", line 111, in ref_will_be_on_timeline
    and self.start_event.date.get_sort_value() <= event.date.get_sort_value()
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'date'
```
There's no problem when opening the family panel and the timeline shows all individuals' dates correctly in the right order, but the line itself isn't there.

**Comment by olivierberten** [comment]
It does :-) Thanks!

But as a matter of fact, for my test tree, I added a family of 3 people with a birth date for each of them so your guess doesn't match...

**Comment by olivierberten** [comment]
Then I guess I should report a bug to Gramps...

Here's my test.gramps:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE database PUBLIC "-//Gramps//DTD Gramps XML 1.7.1//EN"
"http://gramps-project.org/xml/1.7.1/grampsxml.dtd">
<database xmlns="http://gramps-project.org/xml/1.7.1/">
  <header>
    <created date="2024-12-26" version="5.2.2"/>
    <researcher>
    </researcher>
  </header>
  <events>
    <event handle="_fc814a6f9fb305c63778e91a66b" change="1735201436" id="E0003">
      <type>Birth</type>
      <dateval val="1987-01-12"/>
    </event>
    <event handle="_fc814b0df332d90b94ee9044b18" change="1735201501" id="E0004">
      <type>Birth</type>
      <dateval val="1980-12-25"/>
    </event>
    <event handle="_fc814b8d63623e987efd8fe7cb6" change="1735201553" id="E0005">
      <type>Birth</type>
      <dateval val="2010-01-01"/>
    </event>
  </events>
  <people>
    <person handle="_fc8149f7236336dc5bb7465f1f3" change="1735201563" id="I0003">
      <gender>M</gender>
      <name type="Birth Name">
        <first>Father</first>
        <surname>Name-One</surname>
      </name>
      <eventref hlink="_fc814a6f9fb305c63778e91a66b" role="Primary"/>
      <parentin hlink="_fc814ab222337686b08128a2be5"/>
    </person>
    <person handle="_fc814ac2c13b4b90041cdbd6b0" change="1735201563" id="I0004">
      <gender>F</gender>
      <name type="Birth Name">
        <first>Mother</first>
        <surname>Name-Two</surname>
      </name>
      <eventref hlink="_fc814b0df332d90b94ee9044b18" role="Primary"/>
      <parentin hlink="_fc814ab222337686b08128a2be5"/>
    </person>
    <person handle="_fc814b306ba545d4c6c14beb4e" change="1735201563" id="I0005">
      <gender>M</gender>
      <name type="Birth Name">
        <first>Child</first>
        <surname>Both-Names</surname>
      </name>
      <eventref hlink="_fc814b8d63623e987efd8fe7cb6" role="Primary"/>
      <childof hlink="_fc814ab222337686b08128a2be5"/>
    </person>
  </people>
  <families>
    <family handle="_fc814ab222337686b08128a2be5" change="1735201563" id="F0001">
      <rel type="Unknown"/>
      <father hlink="_fc8149f7236336dc5bb7465f1f3"/>
      <mother hlink="_fc814ac2c13b4b90041cdbd6b0"/>
      <childref hlink="_fc814b306ba545d4c6c14beb4e"/>
    </family>
  </families>
</database>

```

**Comment by olivierberten** [comment]
It seems indeed to be a problem with my install because it affects other graphic views as well, with pretty much all my trees. I'll have to dig deeper in order to find out what's happening...
